name: CD

on:
  push:
    tags:
      - '*'
  workflow_dispatch:

jobs:
  Linux-OpenCL:
    name: Linux OpenCL

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v7
      with:
        fetch-depth: 0
        fetch-tags: true
    - name: Script
      run: |
        docker run --rm -i -v "$GITHUB_WORKSPACE:/workspace" -w /workspace centos:7 bash -s -e -o pipefail <<'EOF'
        sed -i '/^mirrorlist/d;/^#baseurl=/{s|^#||;s|/mirror|/vault|;}' /etc/yum.repos.d/CentOS*.repo
        # yum update -y
        yum install -y centos-release-scl epel-release
        sed -i '/^mirrorlist/d;/^# *baseurl=/{s|^# *||;s|/mirror|/vault|;}' /etc/yum.repos.d/CentOS-SCLo-*.repo
        yum install -y devtoolset-11-gcc-c++ devtoolset-11-libstdc++-static make git ocl-icd-devel

        source /opt/rh/devtoolset-11/enable
        g++ --version
        ldd --version

        make STATIC_RUNTIME=1 -j "$(nproc)"
        cd build-release
        rm -f -- *.o
        ./prpll -h
        EOF
    - uses: actions/upload-artifact@v7
      with:
        name: PRPLL-NTT_Linux_x64_opencl
        path: |
          README.*
          LICENSE
          tools/*
          build-release/*

  Linux-CUDA:
    name: Linux CUDA

    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
        - cuda: '13.2.1'
          container: 'rockylinux8'
        - cuda: '12.9.2'
          container: 'rockylinux8'
        - cuda: '11.8.0'
          container: 'centos7'
        - cuda: '10.2'
          container: 'centos7'
      fail-fast: false
    steps:
    - uses: actions/checkout@v7
      with:
        fetch-depth: 0
        fetch-tags: true
    - name: Script
      run: |
        docker run --rm -i -v "$GITHUB_WORKSPACE:/workspace" -w /workspace "nvcr.io/nvidia/cuda:${{ matrix.cuda }}-devel-${{ matrix.container }}" bash -s -e -o pipefail <<'EOF'
        if [[ "${{ matrix.container }}" == centos* ]]; then
          sed -i '/^mirrorlist/d;/^#baseurl=/{s|^#||;s|/mirror|/vault|;}' /etc/yum.repos.d/CentOS*.repo
          # yum update -y
          yum install -y centos-release-scl epel-release
          sed -i '/^mirrorlist/d;/^# *baseurl=/{s|^# *||;s|/mirror|/vault|;}' /etc/yum.repos.d/CentOS-SCLo-*.repo
          yum install -y devtoolset-11-gcc-c++ devtoolset-11-libstdc++-static make git
          source /opt/rh/devtoolset-11/enable
        else
          # dnf update -y
          dnf install -y gcc-toolset-11-gcc-c++ make git
          source /opt/rh/gcc-toolset-11/enable
        fi

        g++ --version
        ldd --version

        make CUDA=1 STATIC_RUNTIME=1 STATIC_CUDA=${{ matrix.cuda != '10.2' && '1' || '0' }} -j "$(nproc)"
        cd build-cuda
        rm -f -- *.o
        if [[ "${{ matrix.cuda }}" == "10.2" ]]; then
          cp -v /usr/local/cuda/lib64/{libnvrtc.so.10.2,libnvrtc-builtins.so.10.2} .
        fi
        # ./prpll -h
        EOF
    - uses: actions/upload-artifact@v7
      with:
        name: PRPLL-NTT_Linux_x64_cuda_${{ matrix.cuda }}
        path: |
          README.*
          LICENSE
          tools/*
          build-cuda/*

  Windows-OpenCL:
    name: Windows OpenCL

    runs-on: windows-2022
    steps:
    - uses: actions/checkout@v7
      with:
        fetch-depth: 0
        fetch-tags: true
    - uses: step-security/msvc-dev-cmd@v1
    - name: Install OpenCL
      run: |
        vcpkg install opencl
    - name: Script
      run: |
        msbuild PRPLL.sln /m /p:Configuration=OpenCL-Release /p:StaticRuntime=true /p:OpenCLRoot=C:\vcpkg\installed\x64-windows
        cd build-msvc\OpenCL\Release\
        & .\prpll -h
    - uses: actions/upload-artifact@v7
      with:
        name: PRPLL-NTT_Windows_x64_opencl
        path: |
          README.*
          LICENSE
          tools/*
          build-msvc/OpenCL/Release/*

  Windows-CUDA:
    name: Windows CUDA

    runs-on: windows-2022
    strategy:
      matrix:
        cuda: ['13.2.1', '12.9.2', '11.8.0', '10.2.89']
      fail-fast: false
    steps:
    - uses: actions/checkout@v7
      with:
        fetch-depth: 0
        fetch-tags: true
    - uses: step-security/msvc-dev-cmd@v1
    - name: Install CUDA Toolkit
      uses: N-Storm/cuda-toolkit@v0.2.34
      with:
        cuda: ${{ matrix.cuda }}
    - name: Script
      run: |
        msbuild PRPLL.sln /m /p:Configuration=CUDA-Release /p:StaticRuntime=true /p:StaticCUDA=${{ matrix.cuda != '10.2.89' && 'true' || 'false' }}
        cd build-msvc\CUDA\Release\
        if ("${{ matrix.cuda }}" -eq "10.2.89") {
          Copy-Item "$env:CUDA_PATH\bin\nvrtc64_102_0.dll", "$env:CUDA_PATH\bin\nvrtc-builtins64_102.dll" .
        }
        # & .\prpll -h
    - uses: actions/upload-artifact@v7
      with:
        name: PRPLL-NTT_Windows_x64_cuda_${{ matrix.cuda }}
        path: |
          README.*
          LICENSE
          tools/*
          build-msvc/CUDA/Release/*

  deploy:
    name: Deploy
    needs: [Linux-OpenCL, Linux-CUDA, Windows-OpenCL, Windows-CUDA]

    runs-on: ubuntu-latest
    steps:
    - uses: actions/download-artifact@v8
    - name: Install
      run: |
        sudo apt-get update -y
        sudo apt-get install -y lftp
    - name: Script
      run: |
        set -x
        ls -alR PRPLL-NTT_*
        for DIR in PRPLL-NTT_*/; do
            (
                cd "$DIR"
                if [[ $DIR == PRPLL-NTT_Windows_* ]]; then
                    zip -r "../${DIR%/}.zip" -- README.* LICENSE tools/
                    zip -j "../${DIR%/}.zip" -- build-msvc/*/Release/*
                else
                    tar -czf "../${DIR%/}.tar.gz" --transform='s|^build-[^/]*/||' README.* LICENSE tools/ build-*/*
                fi
            )
        done
        ls -alR PRPLL-NTT_*
        lftp -u '${{ secrets.FTP_USERNAME }},${{ secrets.FTP_PASSWORD }}' -e 'set cmd:fail-exit true; set ssl:check-hostname false; cd /PRPLL-NTT; mput PRPLL-NTT_*.zip PRPLL-NTT_*.tar.gz; exit' download.mersenne.ca
